### ISSUE TITLE
Android snapshot generation fails

### ISSUE THREAD

**Issue by prabudevarrajan1** [NativeScript/mksnapshot-tools#52]
My current mac OS is Mojave(10.14.6). I upgraded the NativeScript and related plugin to latest version, particularly webpack. Also, installed the Dockers and started the server. 

Nativescript version - 6.3.0
"@ngtools/webpack": "8.0.0",
"nativescript-dev-webpack": "^1.4.0",

During "tns build android --release --bundle --env.uglify --env.aot --env.snapshot", I am getting below error. 

```
ERROR in NativeScriptSnapshot. Snapshot generation failed!
Target architecture: armeabi-v7a
docker: Error response from daemon: Mounts denied: 
The paths /Library/WebServer/Documents/myApp/platforms/android/app/snapshot-build/build/snapshots/blobs/armeabi-v7a and /Library/WebServer/Documents/myApp/platforms/android/app/src/main/assets/app
are not shared from OS X and are not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
.
time="2020-01-02T19:15:51-08:00" level=error msg="error waiting for container: context canceled"
```

Can you please provide clear instruction on how to setup the Dockers "File Sharing". My current setup is default(see screenshot).

![image](https://user-images.githubusercontent.com/2067849/71711404-b52a4c00-2db5-11ea-87d3-25bf08768e60.png)

**Comment by darind** [comment]
As shown in your screenshot only the `/Users`, `/Volumes`, `/private` and `/tmp` paths are exported by MacOS. You are attempting to run your app from `/Library` and hence this path needs to be exported as well. Try adding it to the docker configuration and restarting the daemon.

**Comment by prabudevarrajan** [comment]
Thanks @darind. Your suggestion worked.
